build: clean
	go build -o bin/perf ./perf/perf.go
	go build -o bin/multiperf ./multiperf/multiperf.go
	go build -o bin/local_lat ./local_lat/local_lat.go
	go build -o bin/remote_lat ./remote_lat/remote_lat.go

clean:
	rm -rf ./bin

.PHONY: clean build




